//! Checksummed string encoding for the 32-byte identity seed.
//!
//! The display/generation form is classic BIP-173 bech32 (no length limit —
//! the same primitive the age-style recipient codec uses) under the HRP
//! `l309-seed-`, returned UPPERCASE: `L309-SEED-1…`. Secrets are loud: the
//! uppercase form is visually unmistakable next to lowercase recipient
//! addresses (`age1…`, `age1pqc…`), mirroring age's `AGE-SECRET-KEY-1…`
//! convention, and the checksum deterministically catches typos and
//! truncation.
//!
//! Parsing accepts two representations:
//!
//! 1. the bech32 form in all-lowercase or all-uppercase (mixed case is
//!    rejected per BIP-173), checksum verified, HRP exactly `l309-seed-`,
//!    payload exactly 32 bytes;
//! 2. raw hex — 64 hex digits, case-insensitive, tolerating a `0x` prefix and
//!    surrounding/internal whitespace — the lowest-common-denominator
//!    interchange form, so a seed generated by any external tool imports.
//!
//! Byte-identical parity sibling of the TypeScript `encodeIdentitySeed` /
//! `parseIdentitySeed` and the Python `encode_identity_seed` /
//! `parse_identity_seed`.

use thiserror::Error;

use crate::recipient::{bech32_decode_no_limit, bech32_encode_no_limit};

/// The bech32 human-readable part of the identity-seed encoding. The trailing
/// hyphen is part of the HRP, so with the bech32 separator `1` the rendered
/// prefix reads `l309-seed-1…`.
pub const IDENTITY_SEED_HRP: &str = "l309-seed-";

/// The exact identity-seed length in bytes.
pub const IDENTITY_SEED_LENGTH: usize = 32;

const SEED_HEX_DIGITS: usize = 64;

/// Errors raised by the identity-seed string codec.
///
/// The variants carry Rust-precise detail; [`code`](SeedEncodingError::code)
/// maps each rejection to the cross-implementation error string pinned by the
/// shared conformance vectors.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum SeedEncodingError {
    /// The encode input is not exactly 32 bytes (carries the observed length).
    #[error("seed must be exactly 32 bytes, got {0}")]
    InvalidSeedLength(usize),

    /// The bech32 form mixes upper and lower case (rejected per BIP-173).
    #[error("identity-seed string mixes upper and lower case; use one case only")]
    MixedCase,

    /// The string claims the `l309-seed-` form but fails bech32 decoding.
    #[error("identity-seed string failed bech32 decoding (checksum, character set, or structure)")]
    BadChecksum,

    /// A valid bech32 string under a foreign HRP, e.g. an age recipient pasted
    /// by mistake (carries the observed HRP).
    #[error("expected the bech32 prefix \"l309-seed-\", got \"{0}\"")]
    WrongHrp(String),

    /// Hex input with a digit count other than 64 (carries the count).
    #[error("hex seed must be exactly 64 hex digits, got {0}")]
    HexLength(usize),

    /// A checksum-valid bech32 payload that is not exactly 32 bytes (carries
    /// the decoded length).
    #[error("identity-seed payload must be exactly 32 bytes, got {0}")]
    PayloadLength(usize),

    /// Input that is neither raw hex nor a plausible `l309-seed-` string.
    #[error("expected a 64-hex-digit seed or an L309-SEED-1… string")]
    Unrecognized,
}

impl SeedEncodingError {
    /// The cross-implementation error code this rejection pins. Every
    /// conforming implementation rejects the same malformed input with the
    /// same code.
    #[must_use]
    pub fn code(&self) -> &'static str {
        match self {
            SeedEncodingError::InvalidSeedLength(_) => "INVALID_SEED_LENGTH",
            SeedEncodingError::MixedCase => "SEED_STRING_MIXED_CASE",
            SeedEncodingError::BadChecksum => "SEED_STRING_BAD_CHECKSUM",
            SeedEncodingError::WrongHrp(_) => "SEED_STRING_WRONG_HRP",
            SeedEncodingError::HexLength(_) | SeedEncodingError::PayloadLength(_) => {
                "SEED_STRING_WRONG_LENGTH"
            }
            SeedEncodingError::Unrecognized => "SEED_STRING_UNRECOGNIZED",
        }
    }
}

/// Encode a 32-byte identity seed to its checksummed display form
/// (`L309-SEED-1…`, ~69 characters).
///
/// # Errors
///
/// Returns [`SeedEncodingError::InvalidSeedLength`] unless the seed is exactly
/// 32 bytes.
pub fn encode_identity_seed(seed: &[u8]) -> Result<String, SeedEncodingError> {
    if seed.len() != IDENTITY_SEED_LENGTH {
        return Err(SeedEncodingError::InvalidSeedLength(seed.len()));
    }
    let lowercase = bech32_encode_no_limit(IDENTITY_SEED_HRP, seed)
        .expect("the fixed l309-seed- HRP is a valid bech32 prefix");
    Ok(lowercase.to_ascii_uppercase())
}

/// Parse an identity seed from either accepted representation (the checksummed
/// bech32 form in a single case, or 64-digit raw hex) back to its 32 raw
/// bytes. The inverse of [`encode_identity_seed`] for the bech32 form.
///
/// # Errors
///
/// Returns the [`SeedEncodingError`] variant naming what was wrong: a
/// mixed-case bech32 string, a failed checksum, a foreign HRP, a wrong payload
/// or hex-digit length, or input that is neither representation.
pub fn parse_identity_seed(input: &str) -> Result<[u8; IDENTITY_SEED_LENGTH], SeedEncodingError> {
    // Hex path: strip ALL whitespace and an optional 0x prefix; if what
    // remains is pure hex it can only be meant as a hex seed (the bech32 form
    // always carries non-hex characters: the HRP's `l`, `s`, and `-`).
    let compact: String = input.chars().filter(|c| !c.is_whitespace()).collect();
    let hex_body = compact
        .strip_prefix("0x")
        .or_else(|| compact.strip_prefix("0X"))
        .unwrap_or(&compact);
    if !hex_body.is_empty() && hex_body.bytes().all(|b| b.is_ascii_hexdigit()) {
        if hex_body.len() != SEED_HEX_DIGITS {
            return Err(SeedEncodingError::HexLength(hex_body.len()));
        }
        let bytes = crate::hex::decode(hex_body).expect("a pure even-length hex string decodes");
        return Ok(bytes.try_into().expect("64 hex digits decode to 32 bytes"));
    }

    // Bech32 path: a single token, so only surrounding whitespace is
    // tolerated. The ASCII-case-insensitive probe decides whether a decode
    // failure is reported as a corrupted seed string or unrecognized input.
    let candidate = input.trim();
    let claimed = candidate.to_ascii_lowercase().starts_with("l309-seed-1");
    let has_ascii_lower = candidate.bytes().any(|b| b.is_ascii_lowercase());
    let has_ascii_upper = candidate.bytes().any(|b| b.is_ascii_uppercase());
    if claimed && has_ascii_lower && has_ascii_upper {
        return Err(SeedEncodingError::MixedCase);
    }
    match bech32_decode_no_limit(candidate) {
        Ok((hrp, payload)) => {
            if hrp != IDENTITY_SEED_HRP {
                return Err(SeedEncodingError::WrongHrp(hrp));
            }
            let len = payload.len();
            payload
                .try_into()
                .map_err(|_| SeedEncodingError::PayloadLength(len))
        }
        Err(_) if claimed => Err(SeedEncodingError::BadChecksum),
        Err(_) => Err(SeedEncodingError::Unrecognized),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_rejects_wrong_seed_lengths() {
        for length in [0usize, 31, 33] {
            assert_eq!(
                encode_identity_seed(&vec![0u8; length]).err(),
                Some(SeedEncodingError::InvalidSeedLength(length)),
            );
        }
    }

    #[test]
    fn round_trips_through_both_cases_and_hex() {
        let seed = [0xabu8; 32];
        let encoded = encode_identity_seed(&seed).unwrap();
        assert!(encoded.starts_with("L309-SEED-1"));
        assert_eq!(parse_identity_seed(&encoded).unwrap(), seed);
        assert_eq!(
            parse_identity_seed(&encoded.to_ascii_lowercase()).unwrap(),
            seed
        );
        assert_eq!(
            parse_identity_seed(&crate::hex::encode(&seed)).unwrap(),
            seed
        );
    }

    #[test]
    fn every_error_variant_maps_to_a_pinned_code() {
        let cases: Vec<(SeedEncodingError, &str)> = vec![
            (
                SeedEncodingError::InvalidSeedLength(31),
                "INVALID_SEED_LENGTH",
            ),
            (SeedEncodingError::MixedCase, "SEED_STRING_MIXED_CASE"),
            (SeedEncodingError::BadChecksum, "SEED_STRING_BAD_CHECKSUM"),
            (
                SeedEncodingError::WrongHrp("age".to_string()),
                "SEED_STRING_WRONG_HRP",
            ),
            (SeedEncodingError::HexLength(63), "SEED_STRING_WRONG_LENGTH"),
            (
                SeedEncodingError::PayloadLength(31),
                "SEED_STRING_WRONG_LENGTH",
            ),
            (SeedEncodingError::Unrecognized, "SEED_STRING_UNRECOGNIZED"),
        ];
        for (error, code) in cases {
            assert_eq!(error.code(), code);
        }
    }
}
